//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBuddy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoBuddy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;item&quot;,&quot;version&quot;:&quot;5.24.1&quot;,&quot;basic&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;&quot;,&quot;group&quot;:&quot;&quot;,&quot;description&quot;:&quot;&quot;,&quot;sanitizedDescription&quot;:&quot;&quot;,&quot;colloq&quot;:&quot;&quot;,&quot;plaintext&quot;:&quot;&quot;,&quot;consumed&quot;:false,&quot;stacks&quot;:1,&quot;depth&quot;:1,&quot;consumeOnFull&quot;:false,&quot;from&quot;:[],&quot;into&quot;:[],&quot;specialRecipe&quot;:0,&quot;inStore&quot;:true,&quot;hideFromAll&quot;:false,&quot;requiredChampion&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;maps&quot;:{&quot;10&quot;:true,&quot;1&quot;:true,&quot;8&quot;:true,&quot;12&quot;:true},&quot;image&quot;:null,&quot;stats&quot;:{&quot;rFlatArmorModPerLevel&quot;:0.0,&quot;rFlatArmorPenetrationMod&quot;:0.0,&quot;rFlatArmorPenetrationModPerLevel&quot;:0.0,&quot;rFlatCritChanceModPerLevel&quot;:0.0,&quot;rFlat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NavGraphSummonersRift {
            get {
                object obj = ResourceManager.GetObject("NavGraphSummonersRift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NavGraphSummonersRiftOld {
            get {
                object obj = ResourceManager.GetObject("NavGraphSummonersRiftOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
